# Generated by Django 3.1.6 on 2021-02-23 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamanoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese una breve descripcion de acuerdo al tamaño, ej: PYME', max_length=80, verbose_name='Tipo*:')),
            ],
            options={
                'verbose_name_plural': 'Tamaños de empresas',
            },
        ),
        migrations.CreateModel(
            name='TipoSociedad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Escriba el tipo de sociedad para la empresa, ej: S.A.S', max_length=80, verbose_name='Tipo de sociedad*:')),
            ],
            options={
                'verbose_name_plural': 'Tipos de sociedades',
            },
        ),
        migrations.AlterField(
            model_name='proyectoempresarial',
            name='persona_contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.proyectoempresarial', verbose_name='Persona contacto:'),
        ),
        migrations.CreateModel(
            name='ModeloNegocio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quien_ayudara', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿Quién ayudara?:')),
                ('como_hace', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿Cómo hace?:')),
                ('que_haces', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿Qué haces?:')),
                ('como_interactuas', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿Cómo interactúas?:')),
                ('a_quien_ayudas', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿A quién ayudas?:')),
                ('que_necesitas', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿Qué necesitas?:')),
                ('como_alcanzarlos', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿Cómo alcanzarlos?:')),
                ('cual_sera_costo', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿Cuál sera el costo?:')),
                ('cuanto_ganaras', models.TextField(blank=True, max_length=1000, null=True, verbose_name='¿Cuánto ganarás?:')),
                ('proyecto_empresarial_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.proyectoempresarial', verbose_name='Id. Proyecto empresarial:')),
            ],
            options={
                'verbose_name_plural': 'Modelos de negocio',
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=80, verbose_name='Nombre completo*:')),
                ('cargo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo:')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad:')),
                ('sexo', models.CharField(blank=True, max_length=2, null=True, verbose_name='Sexo:')),
                ('es_lider', models.BooleanField(blank=True, choices=[(True, 'Si'), (False, 'No')], null=True, verbose_name='¿Es lider?:')),
                ('nivel_estudio_id', models.ForeignKey(help_text='Seleccione una identificacion para el nivel de estudios', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.integrante', verbose_name='Id. Nivel de estudio:')),
                ('ocupacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.integrante', verbose_name='Ocupación:')),
                ('profesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.integrante', verbose_name='Profesión:')),
                ('proyecto_empresarial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.proyectoempresarial', verbose_name='Proyecto empresarial:')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionContactoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celular', models.CharField(max_length=15, verbose_name='Celular 1*:')),
                ('celular_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular 2:')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefono fijo:')),
                ('correo_electronico', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email:')),
                ('instagram', models.CharField(blank=True, max_length=60, null=True, verbose_name='Insatagram:')),
                ('facebook', models.CharField(blank=True, max_length=60, null=True, verbose_name='Facebook:')),
                ('otro_barrio', models.CharField(blank=True, max_length=40, null=True, verbose_name='Barrio 2:')),
                ('direccion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Dirección:')),
                ('barrio_id', models.ForeignKey(help_text='Seleccione una identificación para el barrio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.informacioncontactoempresa', verbose_name='Id. Barrio:')),
                ('departamento_id', models.ForeignKey(help_text='Seleccione una identificación para el departamento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.informacioncontactoempresa', verbose_name='Id. Departamento:')),
                ('division_territorial_id', models.ForeignKey(help_text='Seleccione una identificación para la division territorial', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.informacioncontactoempresa', verbose_name='Id. Division territorial:')),
                ('municipio_id', models.ForeignKey(help_text='Seleccione una identificación para el municipio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.informacioncontactoempresa', verbose_name='Id. Municipio:')),
                ('pais_id', models.ForeignKey(help_text='Seleccione una identificación para el pais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.informacioncontactoempresa', verbose_name='Id. Pais:')),
                ('proyecto_empresarial_id', models.ForeignKey(blank=True, help_text='Seleccione una identificacion de proyecto empresarial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.proyectoempresarial', verbose_name='Id. Proyecto empresarial:')),
            ],
            options={
                'verbose_name_plural': 'Contactos de empresas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=11, verbose_name='Nit*:')),
                ('razon_social', models.CharField(max_length=30, verbose_name='Razon Social*:')),
                ('fecha_formalizacion', models.CharField(help_text='Fecha en que la empresa se constituyo legalmente', max_length=30, verbose_name='Fecha de formalizacion*:')),
                ('cubrimiento', models.CharField(blank=True, help_text='Zona de cubrimiento de la empres', max_length=1, null=True, verbose_name='Cubrimiento:')),
                ('proyecto_empresarial_id', models.ForeignKey(blank=True, help_text='Seleccione una identificacion para el proyecto empresarial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.proyectoempresarial', verbose_name='Id. Proyecto empresarial:')),
                ('tamano_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.tamanoempresa', verbose_name='Tamaño de la empresa:')),
                ('tipo_sociedad_id', models.ForeignKey(blank=True, help_text='Seleccione una identificacion para el tipo de sociedad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.tiposociedad', verbose_name='Id. Sociedad:')),
            ],
        ),
    ]
