# Generated by Django 3.1.6 on 2021-02-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20210223_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoempresarial',
            name='persona_contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aplicacion.proyectoempresarial', verbose_name='Persona contacto:'),
        ),
    ]
